# Generated by Django 2.2.3 on 2019-07-31 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190731_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='lastname',
        ),
    ]
