# Generated by Django 2.2.3 on 2019-07-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190727_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(default='08515', max_length=10),
            preserve_default=False,
        ),
    ]
