# Generated by Django 2.2.3 on 2019-07-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(default='photo1', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
